<?php
/**
 * The field order of Grapevine's character exchange format, per race: which scalars, trait lists and tail fields each
 * of the 12 Grapevine character classes reads and writes, in write order. Data only: one `return [...]` array, one
 * entry per `GEX_Parser::RACE_TYPE_MAP` race. It carries no Beyond Elysium block slugs, field labels or per-chronicle
 * settings.
 *
 * `min_version` on a `trait_lists` row is a read gate the shared trait-list loop honours; on a `scalars` row it records
 * the format version that added the field.
 *
 * Field types: `string`, `int16`, `int32`, `bool`, `date`, and `single` (a VB6 `Single`, read via
 * `GV_Binary_Reader::single()`, used only for werewolf and fera's `temp_honor`, `temp_glory` and `temp_wisdom`).
 *
 * `xml_omit` marks a scalar or bool the writer omits when the value equals that constant. `xml_omit_if` marks one
 * omitted when it equals another named field's value: a `temp_*` field equal to its permanent counterpart, or a
 * `social_max` or `mental_max` equal to `physical_max`.
 *
 * `xml_enum` (wraith's `ethnos` only) maps the binary format's raw int32 to the XML format's 3-value string.
 *
 * Every race's `HangoutList` is registered under the string `"Locations"`, except fera's, which is `"Location"`
 * (singular). Every `trait_lists` row uses the name as written on the wire.
 */

defined( 'ABSPATH' ) || exit;

return [

	'vampire' => [
		'race_code' => 2,
		'xml_tag'   => 'vampire',
		'scalars'   => [
			[ 'key' => 'name',       'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'nature',     'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor',   'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'clan',       'type' => 'string', 'xml' => 'clan' ],
			[ 'key' => 'sect',       'type' => 'string', 'xml' => 'sect' ],
			[ 'key' => 'coterie',    'type' => 'string', 'xml' => 'coterie', 'min_version' => 2.395 ],
			[ 'key' => 'sire',       'type' => 'string', 'xml' => 'sire', 'min_version' => 2.399 ],
			[ 'key' => 'generation', 'type' => 'int16',  'xml' => 'generation' ],
			[ 'key' => 'title',      'type' => 'string', 'xml' => 'title' ],
			[ 'key' => 'blood',             'type' => 'int16', 'xml' => 'blood' ],
			[ 'key' => 'temp_blood',        'type' => 'int16', 'xml' => 'tempblood',        'xml_omit_if' => 'blood',        'min_version' => 2.397 ],
			[ 'key' => 'willpower',         'type' => 'int16', 'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower',    'type' => 'int16', 'xml' => 'tempwillpower',    'xml_omit_if' => 'willpower',    'min_version' => 2.397 ],
			[ 'key' => 'conscience',        'type' => 'int16', 'xml' => 'conscience' ],
			[ 'key' => 'temp_conscience',   'type' => 'int16', 'xml' => 'tempconscience',   'xml_omit_if' => 'conscience',   'min_version' => 2.397 ],
			[ 'key' => 'self_control',      'type' => 'int16', 'xml' => 'selfcontrol' ],
			[ 'key' => 'temp_self_control', 'type' => 'int16', 'xml' => 'tempselfcontrol', 'xml_omit_if' => 'self_control', 'min_version' => 2.397 ],
			[ 'key' => 'courage',           'type' => 'int16', 'xml' => 'courage' ],
			[ 'key' => 'temp_courage',      'type' => 'int16', 'xml' => 'tempcourage',      'xml_omit_if' => 'courage',      'min_version' => 2.397 ],
			[ 'key' => 'path',              'type' => 'string', 'xml' => 'path' ],
			[ 'key' => 'path_traits',       'type' => 'int16', 'xml' => 'pathtraits' ],
			[ 'key' => 'temp_path_traits',  'type' => 'int16', 'xml' => 'temppathtraits',  'xml_omit_if' => 'path_traits',  'min_version' => 2.397 ],
			[ 'key' => 'aura',       'type' => 'string', 'xml' => 'aura', 'min_version' => 2.399 ],
			[ 'key' => 'aura_bonus', 'type' => 'string', 'xml' => 'aurabonus', 'xml_omit' => '+0', 'min_version' => 2.399 ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax', 'min_version' => 2.397 ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'player',       'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',       'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',           'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date',   'type' => 'date',   'xml' => 'startdate', 'min_version' => 2.397 ],
			[ 'key' => 'narrator',     'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',       'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date',  'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Status',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Bonds',             'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Miscellaneous',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Derangements',      'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Disciplines',       'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Rituals',           'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5, 'min_version' => 2.395 ],
		],
		'boons' => true,
		'tail'  => [
			[ 'key' => 'biography', 'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',     'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'werewolf' => [
		'race_code' => 3,
		'xml_tag'   => 'werewolf',
		'scalars'   => [
			[ 'key' => 'name',      'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'nature',    'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor',  'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'tribe',     'type' => 'string', 'xml' => 'tribe' ],
			[ 'key' => 'breed',     'type' => 'string', 'xml' => 'breed' ],
			[ 'key' => 'auspice',   'type' => 'string', 'xml' => 'auspice' ],
			[ 'key' => 'rank',      'type' => 'string', 'xml' => 'rank' ],
			[ 'key' => 'pack',      'type' => 'string', 'xml' => 'pack' ],
			[ 'key' => 'totem',     'type' => 'string', 'xml' => 'totem' ],
			[ 'key' => 'camp',      'type' => 'string', 'xml' => 'camp' ],
			[ 'key' => 'position',  'type' => 'string', 'xml' => 'position' ],
			[ 'key' => 'notoriety', 'type' => 'int16',  'xml' => 'notoriety', 'xml_omit' => 0 ],
			[ 'key' => 'rage',           'type' => 'int16', 'xml' => 'rage' ],
			[ 'key' => 'temp_rage',      'type' => 'int16', 'xml' => 'temprage',      'xml_omit_if' => 'rage',      'min_version' => 2.397 ],
			[ 'key' => 'gnosis',         'type' => 'int16', 'xml' => 'gnosis' ],
			[ 'key' => 'temp_gnosis',    'type' => 'int16', 'xml' => 'tempgnosis',    'xml_omit_if' => 'gnosis',    'min_version' => 2.397 ],
			[ 'key' => 'willpower',      'type' => 'int16', 'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower', 'type' => 'int16', 'xml' => 'tempwillpower', 'xml_omit_if' => 'willpower', 'min_version' => 2.397 ],
			[ 'key' => 'honor',      'type' => 'int16',  'xml' => 'honor',  'min_version' => 2.395 ],
			[ 'key' => 'glory',      'type' => 'int16',  'xml' => 'glory',  'min_version' => 2.395 ],
			[ 'key' => 'wisdom',     'type' => 'int16',  'xml' => 'wisdom', 'min_version' => 2.395 ],
			[ 'key' => 'temp_honor', 'type' => 'single', 'xml' => 'temphonor' ],
			[ 'key' => 'temp_glory', 'type' => 'single', 'xml' => 'tempglory' ],
			[ 'key' => 'temp_wisdom','type' => 'single', 'xml' => 'tempwisdom' ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax', 'min_version' => 2.397 ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'player',       'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',       'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',           'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date',   'type' => 'date',   'xml' => 'startdate', 'min_version' => 2.397 ],
			[ 'key' => 'narrator',     'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',       'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date',  'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Features',          'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Gifts',             'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Rites',             'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Honor',             'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Glory',             'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Wisdom',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5, 'min_version' => 2.395 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'biography', 'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',     'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'mortal' => [
		'race_code' => 4,
		'xml_tag'   => 'mortal',
		'scalars'   => [
			[ 'key' => 'name',        'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'nature',      'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor',    'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'motivation',  'type' => 'string', 'xml' => 'motivation' ],
			[ 'key' => 'association', 'type' => 'string', 'xml' => 'association' ],
			[ 'key' => 'regnant',     'type' => 'string', 'xml' => 'regnant', 'min_version' => 2.399 ],
			[ 'key' => 'title',       'type' => 'string', 'xml' => 'title' ],
			[ 'key' => 'willpower',         'type' => 'int16', 'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower',    'type' => 'int16', 'xml' => 'tempwillpower',    'xml_omit_if' => 'willpower',    'min_version' => 2.397 ],
			[ 'key' => 'humanity',          'type' => 'int16', 'xml' => 'humanity' ],
			[ 'key' => 'temp_humanity',     'type' => 'int16', 'xml' => 'temphumanity',     'xml_omit_if' => 'humanity',     'min_version' => 2.397 ],
			[ 'key' => 'conscience',        'type' => 'int16', 'xml' => 'conscience' ],
			[ 'key' => 'temp_conscience',   'type' => 'int16', 'xml' => 'tempconscience',   'xml_omit_if' => 'conscience',   'min_version' => 2.397 ],
			[ 'key' => 'self_control',      'type' => 'int16', 'xml' => 'selfcontrol' ],
			[ 'key' => 'temp_self_control', 'type' => 'int16', 'xml' => 'tempselfcontrol', 'xml_omit_if' => 'self_control', 'min_version' => 2.397 ],
			[ 'key' => 'courage',           'type' => 'int16', 'xml' => 'courage' ],
			[ 'key' => 'temp_courage',      'type' => 'int16', 'xml' => 'tempcourage',      'xml_omit_if' => 'courage',      'min_version' => 2.397 ],
			[ 'key' => 'blood',             'type' => 'int16', 'xml' => 'blood' ],
			[ 'key' => 'temp_blood',        'type' => 'int16', 'xml' => 'tempblood',        'xml_omit_if' => 'blood',        'min_version' => 2.397 ],
			[ 'key' => 'true_faith',        'type' => 'int16', 'xml' => 'truefaith' ],
			[ 'key' => 'temp_true_faith',   'type' => 'int16', 'xml' => 'temptruefaith',   'xml_omit_if' => 'true_faith',   'min_version' => 2.397 ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax', 'min_version' => 2.397 ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'player',       'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',       'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',           'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date',   'type' => 'date',   'xml' => 'startdate' ],
			[ 'key' => 'narrator',     'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',       'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date',  'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Humanity',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Derangements',      'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Numina',            'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5, 'min_version' => 2.395 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'other',     'type' => 'string', 'xml_cdata' => 'other' ],
			[ 'key' => 'biography', 'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',     'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'changeling' => [
		'race_code' => 5,
		'xml_tag'   => 'changeling',
		'scalars'   => [
			[ 'key' => 'name',            'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'seelie_legacy',    'type' => 'string', 'xml' => 'seelie' ],
			[ 'key' => 'unseelie_legacy',  'type' => 'string', 'xml' => 'unseelie' ],
			[ 'key' => 'court',            'type' => 'string', 'xml' => 'court' ],
			[ 'key' => 'kith',             'type' => 'string', 'xml' => 'kith' ],
			[ 'key' => 'seeming',          'type' => 'string', 'xml' => 'seeming' ],
			[ 'key' => 'house',            'type' => 'string', 'xml' => 'house' ],
			[ 'key' => 'threshold',        'type' => 'string', 'xml' => 'threshold' ],
			[ 'key' => 'title',            'type' => 'string', 'xml' => 'title' ],
			[ 'key' => 'glamour',          'type' => 'int16',  'xml' => 'glamour' ],
			[ 'key' => 'temp_glamour',     'type' => 'int16',  'xml' => 'tempglamour',  'xml_omit_if' => 'glamour',  'min_version' => 2.397 ],
			[ 'key' => 'banality',         'type' => 'int16',  'xml' => 'banality' ],
			[ 'key' => 'temp_banality',    'type' => 'int16',  'xml' => 'tempbanality', 'xml_omit_if' => 'banality', 'min_version' => 2.397 ],
			[ 'key' => 'willpower',        'type' => 'int16',  'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower',   'type' => 'int16',  'xml' => 'tempwillpower', 'xml_omit_if' => 'willpower', 'min_version' => 2.397 ],
			[ 'key' => 'physical_max',     'type' => 'int16',  'xml' => 'physicalmax', 'min_version' => 2.397 ],
			[ 'key' => 'social_max',       'type' => 'int16',  'xml' => 'socialmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'mental_max',       'type' => 'int16',  'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'player',           'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',           'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',               'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date',       'type' => 'date',   'xml' => 'startdate', 'min_version' => 2.397 ],
			[ 'key' => 'narrator',         'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',           'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified',    'type' => 'date',   'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Status',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Arts',              'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Realms',            'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5, 'min_version' => 2.395 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'oaths',     'type' => 'string', 'xml_cdata' => 'oaths' ],
			[ 'key' => 'biography', 'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',     'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'wraith' => [
		'race_code' => 6,
		'xml_tag'   => 'wraith',
		'scalars'   => [
			[ 'key' => 'name', 'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'ethnos', 'type' => 'int32', 'xml' => 'ethnos', 'xml_enum' => [ 0 => 'Wraith', 1 => 'Risen', 2 => 'Spectre' ] ],
			[ 'key' => 'nature',           'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor',         'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'guild',            'type' => 'string', 'xml' => 'guild' ],
			[ 'key' => 'faction',          'type' => 'string', 'xml' => 'faction' ],
			[ 'key' => 'legion',           'type' => 'string', 'xml' => 'legion' ],
			[ 'key' => 'rank',             'type' => 'string', 'xml' => 'rank' ],
			[ 'key' => 'pathos',           'type' => 'int16',  'xml' => 'pathos' ],
			[ 'key' => 'temp_pathos',      'type' => 'int16',  'xml' => 'temppathos', 'xml_omit_if' => 'pathos',   'min_version' => 2.397 ],
			[ 'key' => 'corpus',           'type' => 'int16',  'xml' => 'corpus' ],
			[ 'key' => 'temp_corpus',      'type' => 'int16',  'xml' => 'tempcorpus', 'xml_omit_if' => 'corpus',   'min_version' => 2.397 ],
			[ 'key' => 'willpower',        'type' => 'int16',  'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower',   'type' => 'int16',  'xml' => 'tempwillpower', 'xml_omit_if' => 'willpower', 'min_version' => 2.397 ],
			[ 'key' => 'shadow_archetype', 'type' => 'string', 'xml' => 'shadowarchetype' ],
			[ 'key' => 'shadow_player',    'type' => 'string', 'xml' => 'shadowplayer' ],
			[ 'key' => 'angst',            'type' => 'int16',  'xml' => 'angst' ],
			[ 'key' => 'temp_angst',       'type' => 'int16',  'xml' => 'tempangst', 'xml_omit_if' => 'angst', 'min_version' => 2.397 ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax', 'min_version' => 2.397 ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'player',     'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',     'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',         'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date', 'type' => 'date',   'xml' => 'startdate', 'min_version' => 2.397 ],
			[ 'key' => 'narrator',   'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',     'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date', 'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Status',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Arcanoi',           'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5, 'min_version' => 2.395 ],
			[ 'name' => 'Thorns',            'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'passions',      'type' => 'string', 'xml_cdata' => 'passions' ],
			[ 'key' => 'fetters',       'type' => 'string', 'xml_cdata' => 'fetters' ],
			[ 'key' => 'life',          'type' => 'string', 'xml_cdata' => 'life' ],
			[ 'key' => 'death',         'type' => 'string', 'xml_cdata' => 'death' ],
			[ 'key' => 'haunt',         'type' => 'string', 'xml_cdata' => 'haunt' ],
			[ 'key' => 'regret',        'type' => 'string', 'xml_cdata' => 'regret' ],
			[ 'key' => 'dark_passions', 'type' => 'string', 'xml_cdata' => 'darkpassions' ],
			[ 'key' => 'notes',         'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'mage' => [
		'race_code' => 7,
		'xml_tag'   => 'mage',
		'scalars'   => [
			[ 'key' => 'name',         'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'nature',       'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor',     'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'essence',      'type' => 'string', 'xml' => 'essence' ],
			[ 'key' => 'tradition',    'type' => 'string', 'xml' => 'tradition' ],
			[ 'key' => 'faction',      'type' => 'string', 'xml' => 'faction' ],
			[ 'key' => 'cabal',        'type' => 'string', 'xml' => 'cabal' ],
			[ 'key' => 'rank',         'type' => 'string', 'xml' => 'rank' ],
			[ 'key' => 'willpower',         'type' => 'int16', 'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower',    'type' => 'int16', 'xml' => 'tempwillpower',    'xml_omit_if' => 'willpower',    'min_version' => 2.397 ],
			[ 'key' => 'arete',             'type' => 'int16', 'xml' => 'arete' ],
			[ 'key' => 'temp_arete',        'type' => 'int16', 'xml' => 'temparete',        'xml_omit_if' => 'arete',        'min_version' => 2.397 ],
			[ 'key' => 'quintessence',      'type' => 'int16', 'xml' => 'quintessence' ],
			[ 'key' => 'temp_quintessence', 'type' => 'int16', 'xml' => 'tempquintessence', 'xml_omit_if' => 'quintessence', 'min_version' => 2.397 ],
			[ 'key' => 'paradox',           'type' => 'int16', 'xml' => 'paradox' ],
			[ 'key' => 'temp_paradox',      'type' => 'int16', 'xml' => 'tempparadox',      'xml_omit_if' => 'paradox',      'min_version' => 2.397 ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax', 'min_version' => 2.397 ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'player',     'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',     'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',         'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date', 'type' => 'date',   'xml' => 'startdate', 'min_version' => 2.397 ],
			[ 'key' => 'narrator',   'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',     'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date', 'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Resonance',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Reputation',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Spheres',           'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Rotes',             'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5, 'min_version' => 2.395 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'foci',      'type' => 'string', 'xml_cdata' => 'foci' ],
			[ 'key' => 'biography', 'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',     'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'fera' => [
		'race_code' => 8,
		'xml_tag'   => 'fera',
		'scalars'   => [
			[ 'key' => 'name',      'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'nature',    'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor',  'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'fera',      'type' => 'string', 'xml' => 'fera' ],
			[ 'key' => 'breed',     'type' => 'string', 'xml' => 'breed' ],
			[ 'key' => 'auspice',   'type' => 'string', 'xml' => 'auspice' ],
			[ 'key' => 'rank',      'type' => 'string', 'xml' => 'rank' ],
			[ 'key' => 'pack',      'type' => 'string', 'xml' => 'pack' ],
			[ 'key' => 'totem',     'type' => 'string', 'xml' => 'totem' ],
			[ 'key' => 'position',  'type' => 'string', 'xml' => 'position' ],
			[ 'key' => 'notoriety', 'type' => 'int16',  'xml' => 'notoriety', 'xml_omit' => 0 ],
			[ 'key' => 'rage',           'type' => 'int16', 'xml' => 'rage' ],
			[ 'key' => 'temp_rage',      'type' => 'int16', 'xml' => 'temprage',      'xml_omit_if' => 'rage',      'min_version' => 2.397 ],
			[ 'key' => 'gnosis',         'type' => 'int16', 'xml' => 'gnosis' ],
			[ 'key' => 'temp_gnosis',    'type' => 'int16', 'xml' => 'tempgnosis',    'xml_omit_if' => 'gnosis',    'min_version' => 2.397 ],
			[ 'key' => 'willpower',      'type' => 'int16', 'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower', 'type' => 'int16', 'xml' => 'tempwillpower', 'xml_omit_if' => 'willpower', 'min_version' => 2.397 ],
			[ 'key' => 'honor',      'type' => 'int16',  'xml' => 'honor',  'min_version' => 2.395 ],
			[ 'key' => 'glory',      'type' => 'int16',  'xml' => 'glory',  'min_version' => 2.395 ],
			[ 'key' => 'wisdom',     'type' => 'int16',  'xml' => 'wisdom', 'min_version' => 2.395 ],
			[ 'key' => 'temp_honor', 'type' => 'single', 'xml' => 'temphonor' ],
			[ 'key' => 'temp_glory', 'type' => 'single', 'xml' => 'tempglory' ],
			[ 'key' => 'temp_wisdom','type' => 'single', 'xml' => 'tempwisdom' ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax' ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max' ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max' ],
			[ 'key' => 'player',     'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',     'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',         'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date', 'type' => 'date',   'xml' => 'startdate' ],
			[ 'key' => 'narrator',   'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',     'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date', 'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Features',          'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Gifts',             'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Rites',             'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Honor',             'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Glory',             'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Wisdom',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Location', 'abc' => true, 'neg' => false, 'atomic' => true, 'display' => 5, 'min_version' => 2.395 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'biography', 'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',     'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'various' => [
		'race_code' => 9,
		'xml_tag'   => 'various',
		'scalars'   => [
			[ 'key' => 'name',     'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'nature',   'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor', 'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'class',    'type' => 'string', 'xml' => 'class' ],
			[ 'key' => 'subclass', 'type' => 'string', 'xml' => 'subclass' ],
			[ 'key' => 'affinity', 'type' => 'string', 'xml' => 'affinity' ],
			[ 'key' => 'plane',    'type' => 'string', 'xml' => 'plane' ],
			[ 'key' => 'brood',        'type' => 'string', 'xml' => 'brood', 'min_version' => 2.397 ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax', 'min_version' => 2.397 ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'player',     'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',     'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',         'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date', 'type' => 'date',   'xml' => 'startdate', 'min_version' => 2.397 ],
			[ 'key' => 'narrator',   'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',     'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date', 'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Tempers',           'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 2 ],
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Powers',            'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5, 'min_version' => 2.395 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'other',     'type' => 'string', 'xml_cdata' => 'other' ],
			[ 'key' => 'biography', 'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',     'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'mummy' => [
		'race_code' => 10,
		'xml_tag'   => 'mummy',
		'scalars'   => [
			[ 'key' => 'name',     'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'amenti',   'type' => 'string', 'xml' => 'amenti' ],
			[ 'key' => 'nature',   'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor', 'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'willpower',      'type' => 'int16', 'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower', 'type' => 'int16', 'xml' => 'tempwillpower', 'xml_omit_if' => 'willpower', 'min_version' => 2.397 ],
			[ 'key' => 'sekhem',         'type' => 'int16', 'xml' => 'sekhem' ],
			[ 'key' => 'temp_sekhem',    'type' => 'int16', 'xml' => 'tempsekhem',    'xml_omit_if' => 'sekhem',    'min_version' => 2.397 ],
			[ 'key' => 'balance',        'type' => 'int16', 'xml' => 'balance' ],
			[ 'key' => 'temp_balance',   'type' => 'int16', 'xml' => 'tempbalance',   'xml_omit_if' => 'balance',   'min_version' => 2.397 ],
			[ 'key' => 'memory',         'type' => 'int16', 'xml' => 'memory' ],
			[ 'key' => 'temp_memory',    'type' => 'int16', 'xml' => 'tempmemory',    'xml_omit_if' => 'memory',    'min_version' => 2.397 ],
			[ 'key' => 'integrity',      'type' => 'int16', 'xml' => 'integrity' ],
			[ 'key' => 'temp_integrity', 'type' => 'int16', 'xml' => 'tempintegrity', 'xml_omit_if' => 'integrity', 'min_version' => 2.397 ],
			[ 'key' => 'joy',            'type' => 'int16', 'xml' => 'joy' ],
			[ 'key' => 'temp_joy',       'type' => 'int16', 'xml' => 'tempjoy',       'xml_omit_if' => 'joy',       'min_version' => 2.397 ],
			[ 'key' => 'ba',             'type' => 'int16', 'xml' => 'ba' ],
			[ 'key' => 'temp_ba',        'type' => 'int16', 'xml' => 'tempba',        'xml_omit_if' => 'ba',        'min_version' => 2.397 ],
			[ 'key' => 'ka',             'type' => 'int16', 'xml' => 'ka' ],
			[ 'key' => 'temp_ka',        'type' => 'int16', 'xml' => 'tempka',        'xml_omit_if' => 'ka',        'min_version' => 2.397 ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax', 'min_version' => 2.397 ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'player',     'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',     'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',         'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date', 'type' => 'date',   'xml' => 'startdate', 'min_version' => 2.397 ],
			[ 'key' => 'narrator',   'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',     'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date', 'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Humanity',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Status',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Hekau',             'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Spells',            'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Rituals',           'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5, 'min_version' => 2.395 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'inheritance', 'type' => 'string', 'xml_cdata' => 'inheritance' ],
			[ 'key' => 'biography',   'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',       'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'kueijin' => [
		'race_code' => 11,
		'xml_tag'   => 'kueijin',
		'scalars'   => [
			[ 'key' => 'name',         'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'nature',       'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor',     'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'dharma',       'type' => 'string', 'xml' => 'dharma' ],
			[ 'key' => 'balance',      'type' => 'string', 'xml' => 'balance' ],
			[ 'key' => 'direction',    'type' => 'string', 'xml' => 'direction' ],
			[ 'key' => 'station',      'type' => 'string', 'xml' => 'station' ],
			[ 'key' => 'po_archetype', 'type' => 'string', 'xml' => 'poarchetype' ],
			[ 'key' => 'hun',                'type' => 'int16', 'xml' => 'hun' ],
			[ 'key' => 'temp_hun',           'type' => 'int16', 'xml' => 'temphun',           'xml_omit_if' => 'hun',           'min_version' => 2.397 ],
			[ 'key' => 'po',                 'type' => 'int16', 'xml' => 'po' ],
			[ 'key' => 'temp_po',            'type' => 'int16', 'xml' => 'temppo',            'xml_omit_if' => 'po',            'min_version' => 2.397 ],
			[ 'key' => 'yin_chi',            'type' => 'int16', 'xml' => 'yinchi' ],
			[ 'key' => 'temp_yin_chi',       'type' => 'int16', 'xml' => 'tempyinchi',       'xml_omit_if' => 'yin_chi',       'min_version' => 2.397 ],
			[ 'key' => 'yang_chi',           'type' => 'int16', 'xml' => 'yangchi' ],
			[ 'key' => 'temp_yang_chi',      'type' => 'int16', 'xml' => 'tempyangchi',      'xml_omit_if' => 'yang_chi',      'min_version' => 2.397 ],
			[ 'key' => 'demon_chi',          'type' => 'int16', 'xml' => 'demonchi' ],
			[ 'key' => 'temp_demon_chi',     'type' => 'int16', 'xml' => 'tempdemonchi',     'xml_omit_if' => 'demon_chi',     'min_version' => 2.397 ],
			[ 'key' => 'dharma_traits',      'type' => 'int16', 'xml' => 'dharmatraits' ],
			[ 'key' => 'temp_dharma_traits', 'type' => 'int16', 'xml' => 'tempdharmatraits', 'xml_omit_if' => 'dharma_traits', 'min_version' => 2.397 ],
			[ 'key' => 'willpower',          'type' => 'int16', 'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower',     'type' => 'int16', 'xml' => 'tempwillpower',     'xml_omit_if' => 'willpower',     'min_version' => 2.397 ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax', 'min_version' => 2.397 ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max', 'min_version' => 2.397 ],
			[ 'key' => 'player',     'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',     'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',         'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date', 'type' => 'date',   'xml' => 'startdate', 'min_version' => 2.397 ],
			[ 'key' => 'narrator',   'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',     'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date', 'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Status',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Guanxi',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Disciplines',       'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Rites',             'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5, 'min_version' => 2.395 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'biography', 'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',     'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'hunter' => [
		'race_code' => 12,
		'xml_tag'   => 'hunter',
		'scalars'   => [
			[ 'key' => 'name',   'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'creed',  'type' => 'string', 'xml' => 'creed' ],
			[ 'key' => 'nature', 'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor', 'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'camp',   'type' => 'string', 'xml' => 'camp' ],
			[ 'key' => 'handle', 'type' => 'string', 'xml' => 'handle' ],
			[ 'key' => 'conviction',      'type' => 'int16', 'xml' => 'conviction' ],
			[ 'key' => 'temp_conviction', 'type' => 'int16', 'xml' => 'tempconviction', 'xml_omit_if' => 'conviction' ],
			[ 'key' => 'willpower',       'type' => 'int16', 'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower',  'type' => 'int16', 'xml' => 'tempwillpower',  'xml_omit_if' => 'willpower' ],
			[ 'key' => 'mercy',           'type' => 'int16', 'xml' => 'mercy' ],
			[ 'key' => 'temp_mercy',      'type' => 'int16', 'xml' => 'tempmercy',      'xml_omit_if' => 'mercy' ],
			[ 'key' => 'vision',          'type' => 'int16', 'xml' => 'vision' ],
			[ 'key' => 'temp_vision',     'type' => 'int16', 'xml' => 'tempvision',     'xml_omit_if' => 'vision' ],
			[ 'key' => 'zeal',            'type' => 'int16', 'xml' => 'zeal' ],
			[ 'key' => 'temp_zeal',       'type' => 'int16', 'xml' => 'tempzeal',       'xml_omit_if' => 'zeal' ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax' ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max' ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max' ],
			[ 'key' => 'player',     'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',     'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',         'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date', 'type' => 'date',   'xml' => 'startdate' ],
			[ 'key' => 'narrator',   'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',     'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date', 'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Derangements',      'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Edges',             'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'biography', 'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',     'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

	'demon' => [
		'race_code' => 13,
		'xml_tag'   => 'demon',
		'scalars'   => [
			[ 'key' => 'house',    'type' => 'string', 'xml' => 'house' ],
			[ 'key' => 'name',     'type' => 'string', 'xml' => 'name' ],
			[ 'key' => 'faction',  'type' => 'string', 'xml' => 'faction' ],
			[ 'key' => 'nature',   'type' => 'string', 'xml' => 'nature' ],
			[ 'key' => 'demeanor', 'type' => 'string', 'xml' => 'demeanor' ],
			[ 'key' => 'torment',         'type' => 'int16', 'xml' => 'torment' ],
			[ 'key' => 'temp_torment',    'type' => 'int16', 'xml' => 'temptorment',    'xml_omit_if' => 'torment' ],
			[ 'key' => 'faith',           'type' => 'int16', 'xml' => 'faith' ],
			[ 'key' => 'temp_faith',      'type' => 'int16', 'xml' => 'tempfaith',      'xml_omit_if' => 'faith' ],
			[ 'key' => 'willpower',       'type' => 'int16', 'xml' => 'willpower' ],
			[ 'key' => 'temp_willpower',  'type' => 'int16', 'xml' => 'tempwillpower',  'xml_omit_if' => 'willpower' ],
			[ 'key' => 'conscience',      'type' => 'int16', 'xml' => 'conscience' ],
			[ 'key' => 'temp_conscience', 'type' => 'int16', 'xml' => 'tempconscience', 'xml_omit_if' => 'conscience' ],
			[ 'key' => 'conviction',      'type' => 'int16', 'xml' => 'conviction' ],
			[ 'key' => 'temp_conviction', 'type' => 'int16', 'xml' => 'tempconviction', 'xml_omit_if' => 'conviction' ],
			[ 'key' => 'courage',         'type' => 'int16', 'xml' => 'courage' ],
			[ 'key' => 'temp_courage',    'type' => 'int16', 'xml' => 'tempcourage',    'xml_omit_if' => 'courage' ],
			[ 'key' => 'physical_max', 'type' => 'int16', 'xml' => 'physicalmax' ],
			[ 'key' => 'social_max',   'type' => 'int16', 'xml' => 'socialmax', 'xml_omit_if' => 'physical_max' ],
			[ 'key' => 'mental_max',   'type' => 'int16', 'xml' => 'mentalmax', 'xml_omit_if' => 'physical_max' ],
			[ 'key' => 'player',     'type' => 'string', 'xml' => 'player' ],
			[ 'key' => 'status',     'type' => 'string', 'xml' => 'status' ],
			[ 'key' => 'id',         'type' => 'string', 'xml' => 'id' ],
			[ 'key' => 'start_date', 'type' => 'date',   'xml' => 'startdate' ],
			[ 'key' => 'narrator',   'type' => 'string', 'xml' => 'narrator' ],
			[ 'key' => 'is_npc',     'type' => 'bool',   'xml' => 'npc', 'xml_omit' => false ],
			[ 'key' => 'last_modified', 'type' => 'date', 'xml' => 'lastmodified' ],
		],
		'experience' => true,
		'trait_lists' => [
			[ 'name' => 'Physical',          'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Social',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Mental',            'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Physical', 'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Social',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Negative Mental',   'abc' => true,  'neg' => true,  'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Abilities',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Influences',        'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Backgrounds',       'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Health Levels',     'abc' => false, 'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Lores',             'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Apocalyptic Form',  'abc' => false, 'neg' => false, 'atomic' => true,  'display' => 5 ],
			[ 'name' => 'Merits',            'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Flaws',             'abc' => true,  'neg' => true,  'atomic' => true,  'display' => 4 ],
			[ 'name' => 'Equipment',         'abc' => true,  'neg' => false, 'atomic' => false, 'display' => 1 ],
			[ 'name' => 'Locations',         'abc' => true,  'neg' => false, 'atomic' => true,  'display' => 5 ],
		],
		'boons' => false,
		'tail'  => [
			[ 'key' => 'biography', 'type' => 'string', 'xml_cdata' => 'biography', 'min_version' => 2.397 ],
			[ 'key' => 'notes',     'type' => 'string', 'xml_cdata' => 'notes' ],
		],
	],

];
